# Site settings
title: Na China com Gregório e Diana
email: 
description: > # this means to ignore newlines until "baseurl:"
  :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nachinacom.gregorioediana.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
